# Generated by Django 3.2 on 2021-04-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfPoster', models.CharField(max_length=100)),
                ('nameOfLocation', models.CharField(max_length=100)),
                ('photoURL', models.TextField()),
                ('Description', models.TextField()),
            ],
        ),
    ]
