# Generated by Django 3.2.1 on 2021-05-07 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                (
                    'label',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('Recommended', 'Recommended'),
                            ('Want to go', 'Want To Go'),
                            ('Quiet', 'Quiet Place'),
                            ('Crowded', 'Crowded Place'),
                            ('Chance to meet', 'Chance To Meet'),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ('active', models.BooleanField(default=False)),
                (
                    'post',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='comments',
                        to='Post.post',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='comments',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
