# Generated by Django 3.1.7 on 2021-04-03 23:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('tag', models.CharField(blank=True, choices=[('Recommended', 'Recommended'), ('Want to go', 'Want To Go'), ('Quite', 'Quite'), ('Chance to meet', 'Chance To Meet')], max_length=20)),
                ('active', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='pickATrip_django_apps.post')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
